### ISSUE TITLE
Is it possible to hook this up to locally hosted LLMs?

### ISSUE THREAD

**Issue by Harry989** [Enerv/ai-horde-discord-bot#2]
I would Like to connect it to my KoboldAI API instead of actually using Horde. Can anyone help me with editing this so that I am able to do it?

**Comment by Harry989** [comment]
Nevermind I figured it out, if anyone wants to know how reopen this.

**Comment by Enerv** [comment]
Sure, just specify the endpoint parameter in the run command, like this:
`npm start -- --tag=Clyde --inspect --endpoint=http://127.0.0.1:5000`
