### ISSUE TITLE
Use bot with different models?

### ISSUE THREAD

**Issue by CD912** [Enerv/ai-horde-discord-bot#3]
Hello, I was wondering if it's possible to run this with models other than Pygmalion 6b. I'm wanting to use Nerybus specifically.

**Comment by Enerv** [comment]
Of course, although the text formatting will remain unchanged for Pygmalion, by running locally on the endpoint you can run any model that uses the Kobold API.

If you want to use AI Horde with a different model, you need to change `models: ['PygmalionAI/pygmalion-6b']` to `models: ['OPT-6.7B-Nerybus-Mix']` or any [here](https://github.com/Enerv/ai-horde-discord-bot/blob/main/index.mjs#L215) (Line 215 in index.mjs file).

**Comment by CD912** [comment]
Thank you very much!
